In [6]:
import numpy as np

a = np.random.randn(5)
print(a)

[-1.50818529 -1.8162612  -0.20290758 -0.08839819  0.36063181]


In [7]:
a.shape

(5,)

In [8]:
print(a.T)

[-1.50818529 -1.8162612  -0.20290758 -0.08839819  0.36063181]


In [9]:
print(np.dot(a,a.T))

5.752468666174391


In [10]:
a = np.random.randn(5,1)
print(a)

[[ 0.35966889]
 [ 0.34010929]
 [-1.22142484]
 [-0.03253735]
 [-0.45869399]]


In [11]:
a.shape

(5, 1)

In [12]:
print(a.T)

[[ 0.35966889  0.34010929 -1.22142484 -0.03253735 -0.45869399]]


In [13]:
print(np.dot(a,a.T))

[[ 1.29361712e-01  1.22326733e-01 -4.39308519e-01 -1.17026740e-02
  -1.64977958e-01]
 [ 1.22326733e-01  1.15674332e-01 -4.15417941e-01 -1.10662565e-02
  -1.56006089e-01]
 [-4.39308519e-01 -4.15417941e-01  1.49187865e+00  3.97419324e-02
   5.60260233e-01]
 [-1.17026740e-02 -1.10662565e-02  3.97419324e-02  1.05867940e-03
   1.49246887e-02]
 [-1.64977958e-01 -1.56006089e-01  5.60260233e-01  1.49246887e-02
   2.10400175e-01]]


In [16]:
a = a.reshape((5,1))

In [17]:
print(a)

[[ 0.35966889]
 [ 0.34010929]
 [-1.22142484]
 [-0.03253735]
 [-0.45869399]]


In [ ]:
 0